---
title: Phase 1 Deliverable 
date: 10-13-2024
author: Zachariah Dellimore, Suhas Narayanan, Jeffi Thomas
format:
    html:
        theme: cosmo
        toc: false
        embed-resources: true
---

## Project Overview and Key Deliverables
1. Personal health and dietary consciousness are at the forefront, our nutritional planner database project aims to bridge the gap between diverse dietary needs and accurate meal planning. This system offers a comprehensive platform for users to customize, track, and analyze their dietary habits, ensuring they meet specific health goals. With a rich food database, integrated recipes, and targeted meal suggestions, the project addresses the challenge of providing tailored dietary solutions for varied individual requirements.

1. Useful Links
    * [Pitch Video](https://cdnapisec.kaltura.com/index.php/extwidget/preview/partner_id/1888231/uiconf_id/28242191/entry_id/1_gz2tt2pm/embed/dynamic)
    * [Design Video]()
    * [Repository](https://github.com/cmsc-vcu/cmsc508-fa2023-prj-nutritionplan-group27#welcome-to-semecter-project-repository)

## Problem Description
1. **Problem Domain:** Health and fitness is becoming more and more mainstream. A major aspect of this is your diet and what you are eating. It just so happens that this is also the hardest part of maintaining your health. There are thousands of websites, programs, and videos online however they are mainly general plans that aren't tailored to individuals. This leads to a lot of people giving up on their diet after a short period of time because of a lack of interest, lack of feasibility, or a lack of results. A proper nutritional plan must be tailored to the individual based on lifestyle, goals, and personal health to prove effective in the long run. 

1. **Need:** This database is needed because of the increased demand for guidance in nutritional planning. The sheer volume of resources all with conflicting information makes it confusing to find a plan that works for you. This nutritional database takes into consideration things like dietary restrictions, allergies, health goals, personal lifestyle, meal preferences, etc all to create a sustainable, effective, and fun nutritional plan.

1. **Context, scope, and perspective:** This database has a wide scope as it can apply to anyone who is interested in a nutritional plan. For example, students, teachers, athletes, patients, trainers, children, etc. 

1. **User roles and use cases:**
    * Individuals seeking dietary plans:
        * Needs: Access to personalized dietary plans, tracking and analysis of food intake, viewing and adding recipes, setting health goals.
        * Usage: Will log in to view or update their profile, input daily food consumption, view recipes, and monitor progress towards their dietary goals.
    * Nutritionists:
        * Needs: Access to client profiles (with permission), ability to customize and assign dietary plans, monitor and provide feedback on client progress, add new dietary plans or modify existing ones.
        * Usage: After accessing a client's profile, they'll review dietary records, adjust meal plans, and provide notes or feedback to the individual
    * Fitness Trainer:
        * Needs: View (with permission) the dietary habits of clients to adjust fitness routines accordingly, and possibly provide input or feedback on the balance between diet and exercise.
        * Usage: After reviewing the dietary intake of a client, they might adjust workout plans to complement the client's nutritional intake.

1. **Security and Privacy:** We need to have concern over user’s personal information like name, email, contact details, and health data (allergies, medical condition, dietary restrictions). We could implement a multi-factor authentication to ensure legitimate user access to the system. We can also Provide a User Awareness & Education overview providing users with information on how their data is used in order to maintain security. 

## Database Design
**Entity-Relationship diagram(ERD):**

    1. High-Level Overview
        ```{dot}
            graph ER {
    layout=neato;
    scale=1.1;
    node [shape=box]; User, MealPlan, Recipe, Goal;
    node [shape=ellipse]; user_id, user_name, user_password, meal_plan_name, recipe_name, recipe_nutrition, goal_name, ingredients, recipe_instructions, goal_description, meal_plan_id, recipe_id, goal_id, user_meal_plan_id, user_goal_id;

    node [shape=diamond,style=filled,color=lightgrey]; using, has, contains;
    
    User -- using [label="n",len=1.5]
    using -- MealPlan [label="1",len=1.5]
    MealPlan -- contains [label="1",len=1.5]
    contains -- Recipe [label="n",len=1.5]
    User -- has [label="1",len=1.5]
    has -- Goal [label="1",len=1.5]
    
    User -- user_id, user_name, user_password, user_meal_plan_id, user_goal_id;
    MealPlan -- meal_plan_name, meal_plan_id;
    Recipe -- recipe_name, recipe_nutrition, ingredients, recipe_instructions, recipe_id;
    Goal -- goal_name, goal_description, goal_id;
    
    user_meal_plan_id [label="meal_plan_id (FK)"];
    user_goal_id [label="goal_id (FK)"];
}

        ```

    2. Granular
        ```{mermaid}
        erDiagram
            User o{--|| MealPlan : using
                User {
                    PRIMARY_KEY user_id
                    string username
                    string password
                    FOREIGN_KEY meal_plan_id
                    FOREIGN_KEY goal_id
                }

                MealPlan {
                    PRIMARY_KEY meal_plan_id
                    string name
                    FOREIGN_KEY recipe_id
                }
            
            MealPlan ||--o{ Recipe : hosts
                MealPlan{}

                Recipe{
                    PRIMARY_KEY recipe_id
                    string name
                    string nutrition
                    string ingredients
                    string instructions
                }

            User ||--|| Goal : has
                User{}

                Goal{
                    PRIMARY_KEY goal_id
                    string name
                    string description
                }
        ```


**Relational Schemas:**

* User
user_id (Primary Key): Integer or unique identifier – - Domain: Unique integers or GUIDs.

username: String – Domain: Alphanumeric characters, certain symbols. Constraint: Must be unique.

password: String – Domain: Alphanumeric characters, symbols. Constraint: Should adhere to password security standards (length, combination of characters, etc.).

* MealPlan:
meal_plan_id (Primary Key): Integer or unique identifier – Domain: Unique integers or GUIDs.

name: String – Domain: Alphanumeric characters, certain symbols.

recipes (Foreign Key pointing to Recipe): List of integers or unique identifiers – Domain: List of unique integers or GUIDs corresponding to Recipe.

* Recipe:
recipe_id (Primary Key): Integer or unique identifier – Domain: Unique integers or GUIDs.
name: String – Domain: Alphanumeric characters, certain symbols.

nutrition: String – Domain: Text format with nutritional details. Constraint: Could have a standard format or units.

ingredients: String – Domain: List or text format detailing ingredients.

instructions: String – Domain: Step-by-step text format.

* Goal:
goal_id (Primary Key): Integer or unique identifier – Domain: Unique integers or GUIDs.

name: String – Domain: Alphanumeric characters, certain symbols.


**Relationships**

* User - MealPlan: One to Many:

One user can have multiple meal plans but each meal plan is used by only one user. This relationship is represented by the foreign key in the MealPlan table pointing to the User's primary key.

* MealPlan - Recipe: Many to Many:

A meal plan can host multiple recipes and a single recipe can be part of multiple meal plans. To efficiently represent this relationship, an intermediary table (junction table) is often used:

* User - Goal: One to One: 

One user has one goal. This is represented by the foreign key in the Goal table pointing to the User's primary key. (However, if you anticipate a user having multiple goals in the future, this relationship may need to change to one-to-many).


**Constraints:**

* User's username must be unique.
* Passwords in the User table should adhere to certain security constraints like minimum length, and a mix of alphanumeric and special characters.


**Functional Dependencies and Normalization:**

* $R_{0}(UserID, UserName, UserPassword, MealPlanID, GoalID)$ with FD(s): $UserID \rightarrow UserName, UserPassword, MealPlanID, GoalID;$
* $R_{1}(MealPlanID, MealPlanName)$ with FD(s): $MealPlanID \rightarrow MealPlanName;$
* $R_{2}(MealPlanID, RecipeId)$ with FD(s): $MealPlanID \rightarrow RecipeId;$
* $R_{3}(RecipeId, RecipeName, Nutrition, Ingredients, Instructions)$ with FD(s): $RecipeID \rightarrow RecipeName, Nutrition, Ingredients, Instructions;$
* $R_{4}(GoalID, Name, Description)$ with FD(s): $GoalID \rightarrow Name, Description;$

Here our functional dependencies show how  UserName, UserPassword, MealPlanID, GoalID can all be determined by UserId; MealPlanName and RecipeId can be determined by MealPlanID; RecipeName, Nutrition, Ingredients, Instructions can be determined by RecipeId; and Description, Name can be determined by GoalId.
To decompose input relation into 3NF:
For each functional dependency of the canonical cover set (merging functional dependencies having the same left-hand attributes) of original relation's functional dependencies, create a relation schema with the attributes in that functional dependency (both sides). Since key {A} is present in at least one of the new 3NF relations, no new relation was created.

**Specific Queries:**

1. Sort users by name alphabetically

    $\theta_{(UserName)} \tau_{(UserName)}$

2. List all users that have losing weight as their goal

    $\theta_{(UserName)} \pi_{(GoalName: "LoseWeight")} (User \bowtie Goal)$

3. List all recipes that contain Egg

    $\theta_{(RecipeName)} \pi_{(Ingredients LIKE "\%Egg\%")} (User \bowtie Goal)$

4. List all the recipes that are less than 750 calories

    $\theta_{(RecipeName)} \pi_{(Nutrition < 750)}$

5. List all the Meal Plans that do not contain peanut butter

    $\theta_{(MealName)} \pi_{NOT(Ingredients LIKE "\%Peanut Butter\%")} (Recipe \bowtie MealPlan)$

6. List the 3 most popular Goals

    $\theta_{(GoalName)} \tau_{\pi_{(Count(GoalID))}} (User \bowtie Goal)$

7. List the 5 most popular Meal Plans

    $\theta_{(MealPlanName)} \tau_{\pi_{(Count(MealPlanName))}} (User \bowtie MealPlan)$

8. List the 5 most popular Meal Plan that users with the losing weight goal use

    $\theta_{(MealPlanName)} \tau_{\pi_{(Count(MealPlanName && GoalName: WeightLoss))}} (User \bowtie Goal \bowtie MealPlan)$

9. List the 5 most popular recipes

    $\theta_{(RecipeName)} \tau_{\pi_{(Count(RecipeName))}} (User \bowtie Meal Plan \bowtie Recipe)$

10. List all users without a meal plan

    $\theta_{(UserName)} \pi_{MealPlanID: Null}$

11. Order recipes by Nutrition

    $\theta_{(RecipeName)} \tau_{(Nutrition)}$

12. List all users with meal plans with salmon

    $\theta_{(UserName)} \pi_{(Ingredients LIKE "Salmon")} (User \bowtie MealPlan \bowtie Recipe)$
    
13. List all users who have the goal set to "lose weight" and has a meal plan

14. Sort by user password

    $\theta_{(UserPassword)} \tau_{(UserPassword)}$

15. Sort the recipes

    $\theta_{(RecipeName)} \tau_{(RecipeName)}$

16. List all recipes that are more than 400 calories

    $\theta_{(RecipeName)} \pi_{(Nutrition > 400)}$

17. Sort by goal name

    $\theta_{(GoalName)} \tau_{(GoalName)}$

18. Number of Users using the ProteinPunch MealPlan

    $\theta_{(UserName)} \pi_{COUNT(MealName: "ProteinPunch")} (User \bowtie MealPlan)$

19. Sort users who have the goal maintaining weight

    $\theta_{(UserName)} \tau_{\pi_{(GoalName: "MaintainWeight")}} (User \bowtie Goal)$

20. Sort by most popular goals

    $\theta_{(GoalName)} \tau_{\pi_{(Count(GoalID))}} (User \bowtie Goal)$

**Sample Data:**

**User Table**

| UserID | UserName | UserPassword | MealPlanID | GoalID |
|--------|----------|--------------|------------|--------|
| 001    | StarNova | WompWomp205! | 002        | 001    |
| 002    | SuhasNar | LeanMch1ne   | 001        | 003    |
| 003    | x_swag_x | D4rkn3ss     | 003        | 002    |
| 004    | TaylorZa | Icantthink1! | 007        | 006    |
| 005    | SwagMan9 | Meow128312   | 002        | 007    |
| 006    | Brorher2 | Bark1298     | 004        | 004    |
| 007    | Groudon3 | Earthwquake1 | 005        | 005    |


**Meal Plan Table**

| MealPlanID | MealPlanName |
|------------|--------------|
| 001        | ProteinPunch |
| 002        | WeightLoss   |
| 003        | WeightGain   |
| 004        | Vegetarian   |
| 005        | Vegan        |
| 006        | Pescatarian  |
| 007        | DirtyBulk    |


**Recipe Junction Table**

| MealPlanID | RecipeId |
|------------|----------|
| 001        | 1        |
| 001        | 2        |
| 001        | 5        |
| 002        | 3        |
| 002        | 4        |
| 002        | 6        |
| 003        | 2        |
| 003        | 5        |
| 003        | 7        |
| 004        | 3        |
| 004        | 4        |
| 004        | 5        |
| 005        | 3        |
| 005        | 4        |
| 006        | 3        |
| 006        | 6        |
| 007        | 2        |
| 007        | 5        |
| 007        | 7        |

Recipe Table

| RecipeId | RecipeName | Nutrition |   Ingredients    |    Instructions   |
|----------|------------|-----------|------------------|-------------------|
| 1        | ChicknRice | 500cal    | Chickn,Rice,etc. | Season Chicken... |
| 2        | SteakBowl  | 782cal    | Steak,Rice,etc.  | Season Steak...   |
| 3        | CaesarSalad|  289cal   | Lettuce,Salt,etc.| Wash Lettuce...   |
| 4        | TofuLasagna|  552cal   | Tofu,Salt,etc.   | Press Tofu...     |
| 5        | StwbyShake |  400cal   | Stwby,Milk,etc.  | Wash stwby ...    |
| 6        | SalmonBake | 452cal    | Salmon,salt,etc. | Cook Salmon ...   |
| 7        | Bigmac     | 899cal    | Beef,Sauce,etc.  | Cook patty  ...   |

Goal Table

| GoalID |      Name      | Description                       |
|--------|----------------|-----------------------------------|
| 1      | WeightLoss     | Lose 20lbs in 6 months            |
| 2      | WeightGain     | Gain healthy 20lbs in 6 months    |
| 3      | MaintainWeight | Maintain within 5lbs for 6 months |
| 4      | Vegetarianism  | Have a vegetarian diet            |
| 5      | Veganism       | Have a vegan diet                 |
| 6      | DirtyBulk      | Gain Weight faster                |
| 7      | Eat Healthier  | Eat more organic foods            |


## Project Management
11. **Draft Project schedule:**
    ```{mermaid}
    gantt
        title A Gantt Diagram
        dateFormat YYYY-MM-DD
        section Section
            Create Basic Website    :a1, 10-15-2023, 7d
            Create Database    :a2, after a1, 14d
            Collect Data    :a3, after a2, 7d
            Finish Website    :a4, after a3, 21d
            Finishing Touches    :a5, after a4, 11d
    ```

    
12. **Video:**