---
title: Phase 1 Deliverable 
date: 10-13-2024
author: Zachariah Dellimore, Suhas Narayanan, Jeffi Thomas
format:
    html:
        theme: cosmo
        toc: false
        embed-resources: true
---

1. Useful Links
    * [Kaltura Video](TODO)
    * [Repository](https://github.com/cmsc-vcu/cmsc508-fa2023-prj-nutritionplan-group27/tree/main)

## Problem Description 
The rising trend in health and fitness has brought a keen focus on diet and nutrition, which is often considered the most challenging aspect of maintaining good health. With countless general websites, programs, and videos available online, many people find it difficult to stick to a diet, mainly due to its lack of personalization, leading to disinterest, impracticality, or unsatisfactory results. An effective nutritional plan must be tailored to each individual, taking into account their lifestyle, objectives, and health conditions. This need is amplified by the overwhelming amount of information available, often with conflicting advice, making it hard to find a suitable plan. Our nutritional database addresses this issue by factoring in dietary restrictions, allergies, health objectives, personal lifestyle, and meal preferences to create a nutritional plan that is not only sustainable and effective but also enjoyable.

### Crows Foot Diagram
The following Crows Foot diagram represents the relationships between the the users, mealplans, recipes, and goals.
```{mermaid}
erDiagram
users }o--|o mealplans : eats
users }o--|o goals : has
mealplans }|--}| recipes : contain


goals{
  PRIMARY_KEY id
  string name
  string description
}

mealplans {
  PRIMARY_KEY id
  string name
}
recipes {
  PRIMARY_KEY id
  string name
  int calories
  string ingredients
  string instructions
}
users {
  PRIMARY_KEY id
  string username
  string password
  string about_me
  FOREIGN_KEY mealplan_id
  FOREIGN_KEY goal_id
}
```

### DDL File Report
The ddl.sql file was utilzed to create mealplans,recipes, mealplanrecipes, goals, and users tables as well as their corresponding primary keys, foreign keys, and entity specific attributes. The dml.sql file was utilzed to insert the actual information into these tables using the "insert into [insert table (name)] values [table values]". The next few following sections explain user functionality and how to create, update, and delete data in the tables using the API. These files are in the src/sql directory or you can find them at this [link](https://github.com/cmsc-vcu/cmsc508-fa2023-prj-nutritionplan-group27/tree/main/src/sql)

## API Definition
Our API has many different methods depending on which topic you are searching for. To access the api the user must first create a new user by going to the /create/user url and put their newly created username and password as argument variables in their api request. Creating a user is the only action a user can do without having a valid username and password in their header variables.

### Arguments
1. 'page': Int argument to get the specified page of data. The page argument has a default value of 1 but if the user wants to go to the second page they would put 2 for the page argument. 
Example: /recipes?page=2

2. 'direction': Int argument to reverse the order of what is returned by the API. Input 1 to reverse the order.
Example: /recipes?direction=1

3. 'username': String only used when creating a new user to set the new user's username

4. 'password': String only used when creating a new user to set the new user's password

### Headers
1. 'username' (required): String of user's account's username
1. 'password' (required): String of user's account's password
1. 'user-id' (optional): Int used on some routes to find a user by their id
1. 'goal-id' (optional): Int used on some routes to find a goal by its id
1. 'recipe-id' (optional): Int used on some routes to find a recipe by its id
1. 'mealplan-id' (optional): Int used on some routes to find a mealplan by its id
1. 'username' (optional): String used on some routes to find similar usernames
1. 'aboutme' (optional): String used on some routes to find similar users with similar aboutmes
1. 'search' (optional): String used on some routes to indicate what to search for
1. 'exclude' (optional): Boolean used on some routes to find all rows that are not similar to the search header. Enter any value to be true, remove from header file to be false.
1. 'limit' (optional): Int used on some routes to find numerical values above/below the limit
1. 'greater_than' (optional): Boolean used on some routes to either find the values above/below the limit
1. 'new-username' (optional): String used on the update route to update the current users username
1. 'new-password' (optional): String used on the update route to update the current users password
1. 'new-aboutme' (optional): String used on the update route to update the current users about me
1. 'new-mealplan' (optional): Int used on the update route to update the current users mealplan
1. 'new-goal' (optional): Int used on the update route to update the current users goal
1. 'recipe-name' (required in some): String used in the /create/recipe route to set the new recipe's name
1. 'recipe-calories' (required in some): Int used in the /create/recipe route to set the new recipe's calorie count
1. 'recipe-ingredients' (required in some): String used in the /create/recipe route to set the new recipe's ingredients
1. 'recipe-instructions' (required in some): String used in the /create/recipe route to set the new recipe's instructions

### Create
To access this functionality you use the /create/ url with either user or recipe appended to it. We only allow people to create users and recipes for simplicity and because it is all a user would ever need to do. 

1. /create/user: Requires the username and password arguments to create a new user and add it to the database.

Example url: /create/user?username=NewUsername&password=NewPassword

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        insert into `users`
        (`username`, `password`) 
        values ("{username}", "{password}");
        """
```

2. /create/recipe: This route requires the name, calories, ingredients, and instructions headers. It will return whether it created an error or whether your recipe was created successfully.

    Example header: 
    {
            
            'username': '[Your Username]',

            'password': '[Your Password]',
            
            'recipe-name': '[Recipe Name]',

            'calories': '[Calorie Count]',

            'ingredients': '[Ingredients]',

            'instructions': '[Instructions]'
    }

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        insert into `recipes`
        (`name`, `calories`, `ingredients`, `instructions`) 
        values ("{name}", "{calories}", "{ingredients}", "{instructions}");
        """
```

### Update
1. /update/user: Requires one or more of the following headers: new-username, new-password, new-about-me, new-mealplan, new-goal

    Example header: 
    {
        
        'username': '[Your Username]',

        'password': '[Your Password]',

        ‘new-password’: ‘[New Password]’
    }

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        UPDATE users
        SET username = '{new_username}'
        WHERE users.username = '{username}';
        """
```

### Delete
Currently we only support a user deleting theirself

1. /delete/user: Will delete the users account using the username and password in the header.

Query: 
```{python}
#| eval: false
#| echo: true
query=f"""
        DELETE FROM
        users
        WHERE username = '{username}';
        """
```

### Users
Currently we only support a user updating their own personal user values

1. /users: This route takes in the standard arguments as well as the header ‘user-id’ which is an integer. If user-id is not given then the api returns all users sorted by their ids. If user-id is given it returns the user with that user-id.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM users
        """
        if(user_id != 0):
            query += f"WHERE users.id = {user_id}"
        query += f"""
        ORDER BY users.id {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};"""
```

2. /users/goals: This route takes in the standard arguments as well as the header ‘goal-id’. If goal-id is not given by the user then it returns all users sorted by their goal-id. If the user does give goal-id it returns all users with that specific goal-id. If goal-id is less than 0 it will return all users without goals.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM users
        """
        if(goal_id != 0):
            if(goal_id < 0):
                query += f"WHERE users.goal_id IS NULL"
            else:
                query += f"WHERE users.goal_id = {goal_id}"
        query += f"""
        ORDER BY users.goal_id {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};"""
```

3. /users/mealplans: This route takes in the standard arguments as well as the header ‘mealplan-id’ which is an integer. If mealplan-id is not given the api returns all users sorted by their mealplan-id. If the user does give mealplan-id it returns all users with that specific mealplan-id. If mealplan-id is less than 0 it will return all users without mealplans.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM users
        """
        if(mealplan_id != 0):
            if(mealplan_id < 0):
                query += f"WHERE users.mealplan_id IS NULL"
            else:
                query += f"WHERE users.mealplan_id = {mealplan_id}"
        query += f"""
        ORDER BY users.mealplan_id {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};"""
```

4. /users/username: This route takes in the standard arguments as well as the header 'search' which is a string. If search is not given the api returns all users sorted by their search. If search is given then it returns all users with usernames similar to that string

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM users
        """
        if(username != ""):
            query += f"WHERE users.username LIKE '%{username}%'"
        query += f"""
        ORDER BY users.username {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};"""
```

5. /users/aboutme: This route takes in the standard arguments as well as the header ‘aboutme’ which is a string. If aboutme is not given it returns all users sorted by their about_me. If aboutme is given it returns all users with an about_me similar to the aboutme the user supplied.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM users
        """
        if(search != ""):
            exclusion = "" if(exclude == False) else "NOT"
            query += f"WHERE {exclusion} users.about_me LIKE '%{search}%'"
        query+= f"""
        ORDER BY users.about_me {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

### Recipes
1. /recipes: This route takes in the standard arguments as well as the ‘recipe-id’ header which is an integer. If the recipe-id header is not given then the API returns all recipes sorted by their id. If recipe-id is given then it returns the recipe with that id.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM recipes
        """
        if(recipe_id != 0):
            query += f"WHERE recipes.id = {recipe_id}"
        query+= f"""
        ORDER BY recipes.id {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

2. /recipes/name: This route takes in the standard arguments as well as the headers ‘search’ and ‘exclude’. The API returns the recipes ordered by name.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM recipes
        """
        if(recipe != ""):
            exclusion = "" if(exclude == False) else "NOT"
            query += f"WHERE {exclusion} recipes.name LIKE '%{recipe}%'"
        query+= f"""
        ORDER BY recipes.name {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

3. /recipes/calories: This route takes in the standard headers as well as the ‘search’, ‘exclude’, ‘limit’, and ‘greater_than’ headers. The API returns the recipes ordered by calories.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM recipes
        """
        if(recipe != ""):
            exclusion = "" if(exclude == False) else "NOT"
            query += f"WHERE {exclusion} recipes.name LIKE '%{recipe}%'"
        query+= f"""
        WHERE recipes.calories {symbol} {limit}
        ORDER BY recipes.calories {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

4. /recipes/ingredients: This route takes in the standard arguments as well as the ‘search’ and ‘exclude’ headers. The API returns the recipes ordered by ingredients.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM recipes
        """
        if(ingredient != ""):
            exclusion = "" if(exclude == False) else "NOT"
            query += f"WHERE {exclusion} recipes.ingredients LIKE '%{ingredient}%'"
        query+= f"""
        ORDER BY recipes.ingredients {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

5. /recipes/popularity: This route takes in the standard arguments as well as the 'recipe-id' headers. The API returns the recipes ordered by their popularity.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM recipes
        """
        if(ingredient != ""):
            exclusion = "" if(exclude == False) else "NOT"
            query += f"WHERE {exclusion} recipes.ingredients LIKE '%{ingredient}%'"
        query+= f"""
        ORDER BY recipes.ingredients {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

### Mealplans
1. /mealplans: This route takes in the standard arguments as well as the ‘mealplan-id’ header. If the mealplan-id header is not given then the API returns all mealplans sorted by their id. If mealplan-id is given then it returns the mealplan with that id.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
            SELECT *
            FROM mealplans
            """
            if(mealplan_id != 0):
                query+=f"WHERE mealplans.id = {mealplan_id}"
            query+=f"""
            ORDER BY mealplans.id {direction}
            LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
            """
```

2. /mealplans/recipe: This route takes in the standard arguments as well as the ‘mealplan-id’, and 'search' headers. the mealplan-id is required and the API will return with an error if one is not given. The search header is optional and lets you find recipes in the given mealplan. The API returns the found recipes ordered by name.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM recipes
        JOIN mealplanRecipes ON recipes.id = mealplanRecipes.recipe_id
        WHERE mealplanRecipes.mealplan_id = {mealplan_id}
        """
        
        if recipe != None:
            query += f"AND recipes.name LIKE '%{recipe}%'"
            
        query += f"""
        ORDER BY recipes.name {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

3. /mealplans/ingredients: This route takes in the standard arguments as well as the 'search' and 'exclude' headers. If search is not given it will return an error telling the user to give a search query. Exclude will return all mealplans without a certain ingredient. This endpoint returns the list ordered by mealplan name.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT m.id AS mealplan_id, m.name, COALESCE(popular_mealplans.mealplan_count, 0) AS times_used
        FROM mealplans m
        JOIN(
            SELECT mealplan_id, count(mealplan_id) as mealplan_count
            FROM users
        """
        if(goal_id != 0):
            exclusion = "" if(exclude == False) else "NOT"
            query += f"WHERE {exclusion} users.goal_id = {goal_id}"
        query+=f"""
            GROUP BY mealplan_id
            ORDER BY mealplan_count {direction}
            LIMIT {page_size} OFFSET {(current_page - 1) * page_size}
        ) AS popular_mealplans
        ON m.id = popular_mealplans.mealplan_id
        """
        if(mealplan_id != 0):
            query += f"WHERE m.id = {mealplan_id}"
        query+=f"""
        ORDER BY times_used {direction};
        """
```

### Goals
1. /goals: This route takes in the standard arguments as well as the 'goal-id' header. If goal-id is not provided it will return the list of goals sorted by id. If goal-id is provided then it will return the goal with that id.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM goals
        """
        if(goal_id != 0):
            query+=f"WHERE goals.id = {goal_id}"
        query+=f"""
        ORDER BY goals.id {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

2. /goals/name: This route takes in the standard arguments as well as the 'search' header. If search is not provided it will return the list of goals sorted by name. If search is provided it will return all goals with similar names to search.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT *
        FROM goals
        """
        if(name != None):
            query+= f"""
            WHERE goals.name LIKE '%{name}%'
            """
        query+=f"""
        ORDER BY goals.name {direction}
        LIMIT {page_size} OFFSET {(current_page - 1) * page_size};
        """
```

3. /goals/popularity: This route takes in the standard arguments as well as the 'goal-id', 'mealplan-id', and 'exclude' headers. If the goal-id is not given it will return the list of most popular goals sorted by their number of users which will be included in the return json. If goal-id is given it will return the goal with that goal-id and the number of users using that goal. If 'mealplan-id' is given it will return the goals sorted by the number of users who use the chose mealplan. The 'exclude' header reverses this and returns the most popular goal of users not using the specified mealplan.

Query: 
```{python}
#| eval: false
#| echo: true
query = f"""
        SELECT g.id AS goal_id, g.name, g.description, COALESCE(popular_goals.goal_count, 0) AS times_used
        FROM goals g
        JOIN(
            SELECT goal_id, count(goal_id) as goal_count
            FROM users
            """
        if(mealplan_id != 0):
            exclusion = "" if(exclude == False) else "NOT"
            query += f"WHERE {exclusion} users.mealplan_id = {mealplan_id}"
        query+=f"""
            GROUP BY goal_id
            ORDER BY goal_count {direction}
            LIMIT {page_size} OFFSET {(current_page - 1) * page_size}
        ) AS popular_goals
        ON g.id = popular_goals.goal_id
        """
        if(goal_id != 0):
            query += f"WHERE g.id = {goal_id}"
        query+=f"""
        ORDER BY times_used {direction};
        """
```

## API in action
```{python}
#| echo: false
#| eval: true
import requests, sys, pandas
url = 'http://localhost:5000'
```
### 1. Sort users by name alphabetically
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1'
}
response = requests.get(url+'/users/username', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 2. List all users that have Eating Healthier as their goal
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'goal-id': '6'
}
response = requests.get(url+'/users/goals', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 3. List all recipes that contain the ingredient Rice
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'search': 'Rice'
}
response = requests.get(url+'/recipes/ingredients', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 4. List all the recipes that are less than 750 calories
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'limit': '750'
}
response = requests.get(url+'/recipes/calories', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 5. List all the Meal Plans that do not contain rice
```{python}
headers = {
    'username': 'tester',
    'password': 'test',
    'search': 'Rice',
    'exclude': 'True'
}
response = requests.get(url+'/mealplans/ingredients', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 6. List the most popular Goals
```{python}
headers = {
    'username': 'tester',
    'password': 'test'
}
response = requests.get(url+'/goals/popularity', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 7. List the most popular Mealplans
```{python}
headers = {
    'username': 'tester',
    'password': 'test'
}
response = requests.get(url+'/mealplans/popularity', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 8. List all users without a meal plan
```{python}
headers = {
    'username': 'tester',
    'password': 'test',
    'mealplan-id': '-1'
}
response = requests.get(url+'/users/mealplans', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 9. List all users who have the "Weight Gain" mealplan and has the "Weight Gain" goal
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'mealplan-id': '3',
    'goal-id': '2'
}
response = requests.get(url+'/users/mealplans', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 10. Sort by user about me
```{python}
headers = {
    'username': 'tester',
    'password': 'test'
}
response = requests.get(url+'/users/aboutme', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 11. Sort by user about me
```{python}
headers = {
    'username': 'tester',
    'password': 'test'
}
response = requests.get(url+'/users/aboutme', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 12. Sort the recipes by name
```{python}
headers = {
    'username': 'tester',
    'password': 'test'
}
response = requests.get(url+'/recipes/name', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 13. List all recipes that are more than 400 calories
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'limit': '400',
    'greater_than': ''
}
response = requests.get(url+'/recipes/calories', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 14. Sort by goal name
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'limit': '400',
    'greater_than': ''
}
response = requests.get(url+'/goals/name', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 15. Number of Users using the ProteinPunch MealPlan
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'mealplan-id': '1'
}
response = requests.get(url+'/mealplans/popularity', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 16. Sort users who have the goal maintaining weight
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'goal-id': '3'
}
response = requests.get(url+'/users/goals', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 17. Sort by most popular goals
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1'
}
response = requests.get(url+'/goals/popularity', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 18. List all users who have the goal set to “lose weight” and has the lose weight meal plan
```{python}
headers = {
    'username': 'dellimorez',
    'password': 'password1',
    'mealplan-id': '2',
    'goal-id': '1'
}
response = requests.get(url+'/users/goals', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 19. Order recipes by Calories
```{python}
headers = {
    'username': 'tester',
    'password': 'test'
}
response = requests.get(url+'/recipes/calories?direction=1', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

### 20. List Goals by popularity of users not using the "Protein Punch" mealplan
```{python}
headers = {
    'username': 'tester',
    'password': 'test',
    'mealplan-id': '1',
    'exclude': 'True'
}
response = requests.get(url+'/goals/popularity', headers=headers)
df = pandas.DataFrame.from_dict(response.json()['results'])
df
```

## Future Considerations
As we look towards the future expansion ( looking at a possible product) of our nutritional database project, several  enhancements stand out, each aiming to significantly elevate the platform's impact and user experience.

Firstly, introducing an Interactive Recipe Customization feature would mark a significant advancement. This would empower users to modify and refine their recipes directly within the database, allowing for a high degree of personalization. Such a feature is not only beneficial for adjusting to personal taste preferences but also essential for correcting any errors, ensuring the recipes evolve and improve over time.

Implementing a reward system where users earn points for consistently logging meals or sticking to meal plans, we add a layer of motivation and fun to the platform. These points could be redeemed for exclusive recipe suggestions or additional customization options, creating an engaging and rewarding user experience.

Lastly, the possibility of Integration with Fitness Trackers opens a new dimension for the project. Collaborating with fitness apps or devices to incorporate exercise data would enable us to provide dietary recommendations that are informed by individual physical activity levels. This holistic approach to health and wellness would offer users a more comprehensive and tailored health management experience.


## Reflection
Overall the project was a success. We picked up a lot of technical skills, including writing SQL queries, working with FLASK, understanding JSON files, creating an API, etc, all while creating our database. Our design changed quite a bit throughout the course of the semester; however, we are very pleased with the way it turned out. We had to update the way our entities related to one another in the initial stages of the project, but once we got that smoothened out, the project went smoothly. The fact the homework assignments were so closely related to the project really helped guide us along. We now have an amazing database with information to help customize and track dietary habits to attain user-specific health goals.